export const SLUGS = {
  Home: '',
  MyActions: 'my-actions',
  Event: 'event',
  Events: 'events',
  EventsMap: 'event-map',
  CreateEvent: 'create-event',
  SportsPartner: 'sports-partner',
  CreateSportsPartnerPost: 'create-sports-partner-post',
  Friends: 'friends',
  Settings: 'settings',
  UserProfile: 'user-profile',
  Chat: 'chat',
  Dashboard: 'dashboard',
};
