apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: mrodl/sportfriends-fe
---
apiVersion: v1
kind: Service
metadata:
  name: fe-srv
spec:
  type: NodePort
  selector:
    app: fe
  ports:
    - name: fe
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30095